// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgIU03sFsLSGgauhDizv-vxlXl7yNQkY',
    appId: '1:134068539303:web:33ebf7c66900c1b9457082',
    messagingSenderId: '134068539303',
    projectId: 'syncowe',
    authDomain: 'syncowe.firebaseapp.com',
    storageBucket: 'syncowe.appspot.com',
    measurementId: 'G-E8CC4P7G7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOp804osvrh58VKBdLsUUBAvFGuQtWs0',
    appId: '1:134068539303:android:3d559dc7adfbec0b457082',
    messagingSenderId: '134068539303',
    projectId: 'syncowe',
    storageBucket: 'syncowe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl27LRIeJLN3JIgM5UoGAQapggCRQpjyg',
    appId: '1:134068539303:ios:6266379eebe56e7c457082',
    messagingSenderId: '134068539303',
    projectId: 'syncowe',
    storageBucket: 'syncowe.appspot.com',
    androidClientId: '134068539303-hsd51mq42b4mjg8moj3oa4dt75dl2qip.apps.googleusercontent.com',
    iosClientId: '134068539303-97p55nbommdmgclnusi4iekjfc9pn0sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncowe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl27LRIeJLN3JIgM5UoGAQapggCRQpjyg',
    appId: '1:134068539303:ios:6266379eebe56e7c457082',
    messagingSenderId: '134068539303',
    projectId: 'syncowe',
    storageBucket: 'syncowe.appspot.com',
    androidClientId: '134068539303-hsd51mq42b4mjg8moj3oa4dt75dl2qip.apps.googleusercontent.com',
    iosClientId: '134068539303-97p55nbommdmgclnusi4iekjfc9pn0sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncowe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvgIU03sFsLSGgauhDizv-vxlXl7yNQkY',
    appId: '1:134068539303:web:4b295e0165fd69b2457082',
    messagingSenderId: '134068539303',
    projectId: 'syncowe',
    authDomain: 'syncowe.firebaseapp.com',
    storageBucket: 'syncowe.appspot.com',
    measurementId: 'G-W29GFR562M',
  );

}